apiVersion: v1
kind: Service
metadata:
  name: bms-service
  namespace: sasank-ns
spec:
  type: LoadBalancer
  selector:
    app: bms
  ports:
  - protocol: TCP
    port: 3030        # External port exposed to users
    targetPort: 3030  # Internal port your app listens on